import { CONFIGURATION_PROPERTIES } from '../types';

export const GLOBAL_CONFIGURATION_KEY = 'CONFIG_CACHE';

export const CONFIGURATION = () =>
  global[GLOBAL_CONFIGURATION_KEY] as CONFIGURATION_PROPERTIES;
